# Generated by Django 5.2.4 on 2025-07-06 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="note",
            old_name="user",
            new_name="owner",
        ),
        migrations.AlterField(
            model_name="note",
            name="created",
            field=models.DateTimeField(auto_now_add=True, verbose_name="date created"),
        ),
        migrations.AlterField(
            model_name="note",
            name="modified",
            field=models.DateTimeField(auto_now=True, verbose_name="date updated"),
        ),
    ]
